/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContainersIndexRouteImport } from './routes/containers.index'
import { Route as ContainersSlugRouteImport } from './routes/containers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/containers/',
  path: '/containers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersSlugRoute = ContainersSlugRouteImport.update({
  id: '/containers/$slug',
  path: '/containers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/containers/$slug': typeof ContainersSlugRoute
  '/containers/': typeof ContainersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/containers/$slug': typeof ContainersSlugRoute
  '/containers': typeof ContainersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/containers/$slug': typeof ContainersSlugRoute
  '/containers/': typeof ContainersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/containers/$slug' | '/containers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/containers/$slug' | '/containers'
  id: '__root__' | '/' | '/containers/$slug' | '/containers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainersSlugRoute: typeof ContainersSlugRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/': {
      id: '/containers/'
      path: '/containers'
      fullPath: '/containers/'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$slug': {
      id: '/containers/$slug'
      path: '/containers/$slug'
      fullPath: '/containers/$slug'
      preLoaderRoute: typeof ContainersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainersSlugRoute: ContainersSlugRoute,
  ContainersIndexRoute: ContainersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
