/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EnquiryReceivedRouteImport } from './routes/enquiry-received'
import { Route as ContainersIndexRouteImport } from './routes/containers.index'
import { Route as ContainersSlugRouteImport } from './routes/containers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryReceivedRoute = EnquiryReceivedRouteImport.update({
  id: '/enquiry-received',
  path: '/enquiry-received',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/containers/',
  path: '/containers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersSlugRoute = ContainersSlugRouteImport.update({
  id: '/containers/$slug',
  path: '/containers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/enquiry-received': typeof EnquiryReceivedRoute
  '/containers/$slug': typeof ContainersSlugRoute
  '/containers/': typeof ContainersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/enquiry-received': typeof EnquiryReceivedRoute
  '/containers/$slug': typeof ContainersSlugRoute
  '/containers': typeof ContainersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/enquiry-received': typeof EnquiryReceivedRoute
  '/containers/$slug': typeof ContainersSlugRoute
  '/containers/': typeof ContainersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/enquiry-received'
    | '/containers/$slug'
    | '/containers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/enquiry-received'
    | '/containers/$slug'
    | '/containers'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/enquiry-received'
    | '/containers/$slug'
    | '/containers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  EnquiryReceivedRoute: typeof EnquiryReceivedRoute
  ContainersSlugRoute: typeof ContainersSlugRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry-received': {
      id: '/enquiry-received'
      path: '/enquiry-received'
      fullPath: '/enquiry-received'
      preLoaderRoute: typeof EnquiryReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/': {
      id: '/containers/'
      path: '/containers'
      fullPath: '/containers/'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$slug': {
      id: '/containers/$slug'
      path: '/containers/$slug'
      fullPath: '/containers/$slug'
      preLoaderRoute: typeof ContainersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  EnquiryReceivedRoute: EnquiryReceivedRoute,
  ContainersSlugRoute: ContainersSlugRoute,
  ContainersIndexRoute: ContainersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
